name: Github Actions FGC
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: 游댣 Build da aplica칞칚o
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do c칩digo
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 游댢 Restaurar e compilar solu칞칚o
      run: dotnet build src\FGC.Api.sln --configuration Release

  test:
    name: Testes Unit치rios
    runs-on: ubuntu-latest
    needs: build  # depende do job de build

    steps:
    - name:  Checkout do c칩digo
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Executar testes
      run: dotnet test src\FGC.Api.sln --no-build --verbosity normal

  push:
    name: 游 Docker Build & Push
    runs-on: ubuntu-latest
    needs: test  # depende do job de test

    steps:
    - name: 游닌 Checkout do c칩digo
      uses: actions/checkout@v4

    - name: 游댏 Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 游냡 Build e Push da imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: vitordietrich/fiap-api:latest
